### PR TITLE
Removing qmk environment until we fix it

### PR DESCRIPTION
**Pull request by floxbot**
This PR was automatically created by [Update workflow](https://github.com/flox/floxenvs/actions/workflows/update.yml).

### CODE REVIEW

**Review by stahnma — APPROVED** [review]

**Review by tomberek — DISMISSED** [review]
Need to check GHA runners.

**Comment by garbas** [comment]
@zmitchell I'm removing the environment but I don't want to. Reason: it is requiring XCode on MacOS and with recent change on macos builder we noticed this. There is still debate if we should allow this in floxenvs environments or not and how we configure our builders. If you find the time to revert this removal and make it not depend on XCode I would be very happy to review it and merge ASAP.

**Review by garbas — APPROVED** [review]

**Comment by zmitchell** [comment]
Makes sense, thanks for the ping

**Comment by tomberek** [comment]
Ah, I started trying to fix it... no prob. Removal is simpler.

**Pull request merged**
